const genText = document.getElementById("gen-text")

genText.addEventListener("click", function() {
  let messages = [
    "Eu te amei, te amo e te amarei para sempre meu amorzão!",
    "Meu amor por você é atemporal.",
    "Sem você, não me sinto completa.",
    "Estou com certeza pensando em você agora.",
    "Eu te amo. Nunca duvide disso.",
    "Somos perfeitos um para o outro.",
    "Não posso viver sem o seu amor.",
    "Estaria perdida sem você.",
    "Eu te adoro.",
    "Você me faz sorrir como nunca.",
    "Meus melhores dias são com você",
    "Mal posso esperar para te abraçar e de dar beijinhos hihi",
    "Estou morrendo de saudades gatinho!",
    "Você me completa em todos os sentidos.",
    "Você é minha alma gêmea, tudo que eu sempre quis.",
    "Tenho orgulho de ser sua.",
    "Você me faz uma pessoa melhor, obrigada por isso.",
    "Encontrei o amor quando te encontrei.",
    "Penso em você 24 horas por dia, 7 dias por semana.",
    "Você me inspira a ser uma pessoa melhor todo dia.",
    "Tenho muito orgulho de você e de quem você se tornou!",
    "Você derrete meu coração todo dia.",
    "Somos pra sempre meu amor!",
    "Você tem meu coração, cuide bem dele.",
    "Você significa o mundo para mim.",
    "Eu te amo mais a cada dia que passa",
    "Seu amor é tudo que eu preciso.",
    "Agradeço todos os dias por ter te encontrado.",
    "Eu te amo mil milhões!",
    "Estou morrendo de saudades de você meu neném!",
    "Saudade do seu cheirinho",
    "Queria você comigo agora meu amor.",
    "Você é meu mundo!",
    "Quero viver tudo ao seu lado meu príncipe!",
    "Cada momento ao seu lado é um tesouro que guardo no coração.",
    "Você é a razão dos meus sorrisos mais felizes.",
    "Te amo nos detalhes mais simples e nos momentos mais grandiosos.",
    "Seu amor é meu abrigo nos dias de tempestade.",
    "Você me completa de maneiras que nunca imaginei.",
    "Você é meu sonho realizado, meu amor eterno.",
    "Cada pensamento meu tem um pouco de você.",
    "Você faz meu mundo brilhar mais forte.",
    "Te amo mais do que todas as estrelas no céu.",
    "Você é a melodia mais doce que toca no meu coração.",
    "Com você, cada dia é uma nova aventura de amor.",
    "Você é a página mais bonita que o destino escreveu na minha vida.",
    "Te amar é minha maior felicidade.",
    "Com você, encontrei o verdadeiro significado do amor.",
    "Você é meu final feliz.",
    "Meu coração é totalmente seu.",
    "Estou do seu lado em todos os momentos meu amor!",
    "Seu sorriso é a luz que ilumina meus dias.",
    "Você é o presente mais lindo que a vida me deu.",
    "Eu te amo até a lua e de volta."
];

  const textEl = document.querySelector(".textMessage")
  textEl.textContent = messages[Math.floor( Math.random()*messages.length )]
})